#!/usr/bin/env python3
"""Regenerate CPU FP32 RoPE goldens using the pinned Hugging Face implementation.

Requires torch==2.9.0+cpu and transformers==4.57.1 in an isolated environment.
The C++ tests consume the checked-in header and have no Python dependency.
"""

import argparse
import hashlib
import inspect
import json
from pathlib import Path
import platform

import torch
import transformers
from transformers import LlamaConfig
from transformers.models.llama.modeling_llama import (
    LlamaRotaryEmbedding,
    apply_rotary_pos_emb,
)


CASES = [
    ("SplitHalfMha", 4, 2, 2, 4.0, None, [0, 1, 7, 8]),
    ("DefaultGqa", 64, 4, 2, 10000.0, None, [0, 1, 2047, 2048]),
    ("LongPositionMqa", 128, 4, 1, 10000.0, None, [0, 4095, 8191, 32768]),
    ("LargeTheta", 128, 2, 2, 500000.0, None, [0, 17, 8192, 32768]),
    ("LinearIdentity", 64, 2, 1, 10000.0, 1.0, [0, 1, 4096, 8192]),
    ("LinearFractional", 128, 4, 2, 10000.0, 2.5, [0, 17, 8192, 32768]),
    ("LinearBelowOne", 64, 2, 1, 10000.0, 0.75, [0, 3, 1024, 8192]),
]


def float_literal(value):
    literal = format(value, ".9g")
    if "." not in literal and "e" not in literal:
        literal += ".0"
    return literal + "F"


def emit_array(name, values, element_type):
    render = float_literal if element_type == "float" else str
    lines = [f"inline constexpr {element_type} {name}[] = {{"]
    for offset in range(0, len(values), 8):
        lines.append("    " + ", ".join(map(render, values[offset : offset + 8])) + ",")
    lines.append("};")
    return "\n".join(lines)


def make_input(tokens, heads, head_dim, generator):
    values = torch.rand((1, heads, tokens, head_dim), generator=generator) * 2 - 1
    # Fixed scales include exact zeros and small values without changing the seed.
    scales = torch.tensor([0.0, 0.001, 0.125, 1.0], dtype=torch.float32)
    return values * scales[torch.arange(head_dim) % scales.numel()]


def token_major(tensor):
    return tensor.transpose(1, 2).contiguous().flatten().tolist()


def generate():
    if torch.__version__ != "2.9.0+cpu" or transformers.__version__ != "4.57.1":
        raise RuntimeError("Use torch==2.9.0+cpu and transformers==4.57.1")
    torch.set_num_threads(1)
    torch.use_deterministic_algorithms(True)
    torch.set_default_dtype(torch.float32)
    seed = 20260907
    generator = torch.Generator(device="cpu").manual_seed(seed)
    declarations = []
    initializers = []
    records = []
    with torch.no_grad():
        for name, dim, q_heads, kv_heads, theta, factor, positions in CASES:
            config = LlamaConfig(
                hidden_size=q_heads * dim,
                head_dim=dim,
                num_attention_heads=q_heads,
                num_key_value_heads=kv_heads,
                max_position_embeddings=8192,
                rope_theta=theta,
                rope_scaling=None if factor is None else {"rope_type": "linear", "factor": factor},
            )
            q = make_input(len(positions), q_heads, dim, generator)
            k = make_input(len(positions), kv_heads, dim, generator)
            position_ids = torch.tensor([positions], dtype=torch.int64)
            rotary = LlamaRotaryEmbedding(config, device="cpu")
            cosine, sine = rotary(q, position_ids)
            q_output, k_output = apply_rotary_pos_emb(q, k, cosine, sine)
            arrays = {
                "Positions": positions,
                "Q": token_major(q),
                "K": token_major(k),
                "QOutput": token_major(q_output),
                "KOutput": token_major(k_output),
            }
            for suffix, values in arrays.items():
                declarations.append(emit_array(name + suffix, values, "int64_t" if suffix == "Positions" else "float"))
            initializers.append(
                f'    {{"{name}", {dim}, {q_heads}, {kv_heads}, {theta!r}, '
                f'{factor if factor is not None else 1.0!r}, {str(factor is not None).lower()}, '
                f'{name}Positions, {name}Q, {name}K, {name}QOutput, {name}KOutput}},'
            )
            records.append({
                "name": name, "head_dim": dim, "q_heads": q_heads, "kv_heads": kv_heads,
                "theta": theta, "linear_factor": factor, "positions": positions,
                "input_sha256": hashlib.sha256(json.dumps([arrays["Q"], arrays["K"]]).encode()).hexdigest(),
            })
    header = """// Generated by tools/generate_rope_hf_fixture.py; do not edit numeric data.
// clang-format off
#ifndef AETHERMIND_TEST_ROPE_HF_V4_57_1_H
#define AETHERMIND_TEST_ROPE_HF_V4_57_1_H

#include <cstdint>
#include <span>
#include <string_view>

namespace aethermind::test::rope_hf {

struct Case {
    std::string_view name;
    int64_t head_dim;
    int64_t q_heads;
    int64_t kv_heads;
    double theta;
    double factor;
    bool linear;
    std::span<const int64_t> positions;
    std::span<const float> q;
    std::span<const float> k;
    std::span<const float> q_output;
    std::span<const float> k_output;
};

""" + "\n\n".join(declarations) + "\n\ninline constexpr Case kCases[] = {\n" + "\n".join(initializers) + "\n};\n\n} // namespace aethermind::test::rope_hf\n\n#endif\n// clang-format on\n"
    import transformers.modeling_rope_utils as rope_utils

    sources = {}
    for obj in (LlamaRotaryEmbedding, rope_utils):
        source = Path(inspect.getfile(obj))
        sources[source.name] = hashlib.sha256(source.read_bytes()).hexdigest()
    manifest = {
        "torch": torch.__version__, "transformers": transformers.__version__,
        "python": platform.python_version(), "machine": platform.machine(),
        "torch_cpu_capability": torch.backends.cpu.get_cpu_capability(),
        "device": "cpu", "dtype": "float32", "threads": 1, "seed": seed,
        "hf_source_sha256": sources,
        "header_sha256": hashlib.sha256(header.encode()).hexdigest(),
        "cases": records,
    }
    return header, json.dumps(manifest, indent=2) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path(__file__).resolve().parents[1] / "tests/unit/backend/cpu/kernels/fixtures")
    parser.add_argument("--check", action="store_true", help="Verify checked-in files without writing")
    args = parser.parse_args()
    header, manifest = generate()
    for name, content in (("rope_hf_v4_57_1.h", header), ("rope_hf_v4_57_1.json", manifest)):
        path = args.output_dir / name
        if args.check:
            if path.read_text() != content:
                raise RuntimeError(f"Fixture differs: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        print(path)


if __name__ == "__main__":
    main()
